server:
  port: ${PORT:5040}

base-url: /api

jwt:
  token:
    secret: "38782F413F4428472B4B6250655368566D597133743676397924422645294840"

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml