server:
  port: ${PORT:5040}

base-url: /api

jwt:
  token:
    secret: ${SECRET}

spring:
  application:
    name: taskManager

  profiles:
    active: ${APP_ENV}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml